apiVersion: v1
kind: Service
# teste
metadata:
  name: frontend-service
  namespace: production
  annotations:
    prometheus.io/scrape: 'true'   # Habilita a coleta
    prometheus.io/port: '80'
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
